### ISSUE TITLE
Memory leak using new window way to display

### ISSUE THREAD

**Issue by sunkehappy** [dogo/SCLAlertView#142]
After I show the alert view many times I find there are memory leak.
![image](https://cloud.githubusercontent.com/assets/2052221/9717346/99374a54-55a4-11e5-8e37-8239aa94aee9.png)

As shown in this picture there are more than 10 windows from 

`[UIApplication sharedApplication].windows`

 Of course I'm using the new window way to display.

I've tried to set the `SCLAlertWindow` to `nil`, set the timer to `nil` in the `fadeOut` method but no luck.

**Comment by dogo** [comment]
@sunkehappy  thanks for reporting.

Hummm the correct way to hide a window is to set the hidden property to YES and to remove it from UIApplication's windows property you just release the window setting all references to nil

Could you please test the "dev" branch commit f12939010402874481396ba89e2b4a6d3726a920 , should be fixed

**Comment by sunkehappy** [comment]
I've tested the newest release. It's not fixed yet. I guess we need to manually remove it from the `windows` array? If it's the correct way I could write the PR, but I'm just not sure whether we should modify the `windows` property of the `UIApplication`.

![image](https://cloud.githubusercontent.com/assets/2052221/9897146/b95d7b6c-5c77-11e5-8e21-63c39dcfdcfa.png)

**Comment by dogo** [comment]
@sunkehappy could you please test again using develop branch?

**Comment by dogo** [comment]
Please update to 0.8.1
